### ISSUE TITLE
Map data as served by server side component of app not loading

### ISSUE THREAD

**Issue by enlore** [mnhrc/mnhrc.github.io#3]
Pulling in @mshenfield and @combinatorist to start conversation on recovering from this and moving the app onto a more stable and transferable infrastructure.

The app attempts to fetch data from the host listed below as defined here: https://github.com/mnhrc/mnhrc.github.io/blob/master/map_controller.js#L7 

The host appears to be alive but isn't talking.

```
12:22:23 › nmap -Pn -p 80,443 69.167.174.162

Starting Nmap 6.47 ( http://nmap.org ) at 2017-07-31 12:22 CDT
Nmap scan report for 69.167.174.162
Host is up.
PORT    STATE    SERVICE
80/tcp  filtered http
443/tcp filtered https

Nmap done: 1 IP address (1 host up) scanned in 3.10 seconds
```

A quick lookup suggests  https://www.liquidweb.com/ as the service provider. Likely an account issue with said provider (or wherever the backend lives).

@jwoodcock or @jasonamyers, let me know if you can offer any clarification on these points. I'm also looking for the repo that's hosting the server side codebase.

**Comment by jasonamyers** [comment]
Oh! that's something @jwoodcock would have setup. It should load data from a google spreadsheet. I don't appear to have access to that spreadsheet anymore, but Marc(sp?) did at one point.  I think Jacques did it that way to handle the spreadsheet parsing outside of javascript

**Comment by enlore** [comment]
I've got access to the spreadsheet through Mark. It does look like a server side script hosted as described above took care of chewing up the spreadsheet and making it available to the client app. Would love to get my hands on that codebase.

**Comment by jasonamyers** [comment]
@jwoodcock would the owner of that piece of code ATM.

**Comment by enlore** [comment]
Cool. Thanks much.

**Comment by jasonamyers** [comment]
Looks like it was just a CORS proxy https://github.com/mnhrc/mnhrc.github.io/commit/fb020d73a4febb7e70e84fae63cb5311269ca112

**Comment by enlore** [comment]
Ah, excellent. That's very helpful. Thanks again.
